- name: Configure Flask Application
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: ['python3', 'python3-pip', 'nginx']
        state: present

    - name: Deploy Flask application
      copy:
        src: /local/path/to/app/
        dest: /var/www/app/
